### ISSUE TITLE
Make both stat reset and stat transfer free

### ISSUE THREAD

**Issue by ViscaBarre** [elementum-games/shinobi-chronicles#122]
Smol request from the community as whole, at least newer players: make the stat transfers free.

### Issue

With how, admittedly, unintuitive the game is, players have a hard time making informed decisions on what stats to train. What stat affects what, how do they matter in combat, how do they even affect bloodlines.

Because of this, it later feels punishing to later find out you have completely borked up your stats.

The only way to fix that, is to either reset ONE stat for free ONCE, or pay 12 dollars/24 kunai to choose one at a time a stat to transfer to.

**You are frankly shit out of luck** if you do not know what to do from the beginning.

![image](https://user-images.githubusercontent.com/91370970/136585227-11edeb11-b264-4ed7-ad3e-18c325f48966.png)

### Solution

Make the game friendly for experimentation and punish less for mistakes.

- Always free stat reset (losing the experience and time spent on increasing the stat is enough)
- Always free stat transfer (the time required for the stat transfer to be complete is enough)
o Does this make stat reset obsolete?
o There is currently a long cooldown for stat transfers to be completed, as well as afterwards before you can transfer a stat for free? This seems a little overkill at a quick glance.

This is especially important from a new player's point of view.

**Comment by jesGallegos** [comment]
I have felt this way for a bit. I think the approach of making stat transfer free (increasing the duration by ~10%-15%) with the AK coming in to **reduce** said duration might be more noob friendly as well as allow more build diversity as it wont lock testing new builds behind a paywall. I support this change.

**Comment by unownram** [comment]
Have absolutely random suggestions for stat stuff.

1. They now cost yen. You no longer lose exp temporarily. The stat slowly transfers to the new stat at a rate of 1/min. This is paused whenever you enter combat. You cannot train anything while this process is ongoing. Cancelling the transfer leaves stats where they currently are, and a new transfer cannot be started for 24 hours. This does not refund yen.
Pros - Allows people to participate, albeit at a suboptimal level, in ai.
Cons - Basically the same as current, punishes people with a financial and time penalty while transfer is ongoing. Also does not address the issue where training is intended to be impactful

2. Make trained/gained stats more impactful than transferred stats. People will want to not transfer. Training is now objectively better.
Pros - Impactful training paths I guess
Cons - Newbies with random stats will feel shafted. Experienced players will use alts to create a perfectly trained character. Complete resetting and training from scratch to achieve optimal stats will be a thing, greatly increasing the grind time. Completely cuts people out from pvp/ai while their stats are being retrained.

2a. Addendum to suggestion 2. Partial, instead of complete resets, with a minimum percent, or amount based on rank, that can be reset
Pros - Resetting to train is potentially no longer a complete block from ai/pvp.
Cons - Can render transfers completely pointless.

3. Novice ninjas (genin or below, or based on exp?) can transfer stats instantly and for free
Pros - Newbies don't have to suffer through the stats in everything useless stage. New ninjas are free to experiment with different builds and specs.
Cons - Newbies often don't have the raw yen needed to play around. Also, the meta at low ranks is vastly different from higher ranks, they may still end up with useless stats. Also does not address the issue where training is intended to be impactful

**Comment by HitoriWoB** [comment]
@levimeahan Would you like to leave this open for further consideration on price reduction options?

I feel like we could fully resolve this with a free premium currency and opening up alternative purchase methods beyond PayPal.

**Comment by levimeahan** [comment]
Agree I think we've made multiple rounds of adjustments recently and do need to follow up with a low AK cost + significant yen cost tier (probably replacing the current "standard") and then this should be addressed.
