### ISSUE TITLE
Ancient market price increase/QoL updates 

### ISSUE THREAD

**Issue by SatoGojo** [elementum-games/shinobi-chronicles#200]
With how much Yen floating around the game, increase "Money per kunai" from 10.0 -> 20.0

Add a sorting option which can view AK from lowest to highest, or vice versa

Add in a faster way to submit single kunai being sold instead of having to redo all of your inputs one by one

**Comment by HitoriWoB** [comment]
Reverse Auction / Yen Offer is an interesting idea.
I don't know that offering a listing increase on price is necessarily needed. I know yen is pretty abundant right now, but gain changes/etc., may be reducing the amount of yen in the game soon.

I'd personally like to see some other form of yen sink to the game, rather than continually update the price per AK to fit the yen surplus. Some idea currently thrown around are offering BL ability training / increased efficiency ability training in exchange for yen.

**Comment by HitoriWoB** [comment]
Reverse auction was attempted but cancelled due to flooding concerns.
Recent update has increased the price of AK.
